- name: Commit and Push changes
        run: |
          git config --global user.name "IPL Bot"
          git config --global user.email "bot@yourdomain.com"
          git add points-table.html
          git commit -m "Auto-update IPL Points Table" || exit 0
          git push
